GET http://localhost:8080/api/user
Accept: application/json
Authorization: Bearer  JgI7XgLI4rkFyjmtjGaCWlNH0lbEA3zhzdgmfiof

###

GET http://localhost:8080/api/animal
Accept: application/json
Authorization: Bearer JgI7XgLI4rkFyjmtjGaCWlNH0lbEA3zhzdgmfiof


